CREATE SEQUENCE IF NOT EXISTS table_empleados_id_seq;
CREATE SEQUENCE IF NOT EXISTS table_usuarios_id_seq;

CREATE TABLE IF NOT EXISTS  EMPLEADOS(
ID integer NOT NULL DEFAULT nextval('table_empleados_id_seq'),
NOMBRE varchar(30) NULL,
APELLIDO varchar(30) NULL,
FECHA_NAC date NULL,
REPORTA_A int NULL,
EXTENSION int NULL,
CONSTRAINT PK_EMPLEADOS PRIMARY KEY (ID));

CREATE TABLE IF NOT EXISTS USUARIO(
ID integer NOT NULL DEFAULT nextval('table_usuarios_id_seq'),
NOMBRE varchar(50) NOT NULL,
EMAIL varchar(50) NOT NULL,
PASSWORD varchar(100) NULL,
CONSTRAINT PK_USUARIOS PRIMARY KEY (ID));